name: EPSI_MSPR_B3-Groupe_MATS
services:
  db:
    image: postgres:latest
    container_name: MSPR-POSTGRES
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "2345:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    build: ./apps/etl
    container_name: MSPR-ETL
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env  # Ce fichier sera copié dynamiquement depuis config/env/
    ports:
      - "8000:8000"
    volumes:
      - ./apps/etl:/app
      

volumes:
  postgres_data: