version: '3.8'

services:
  krakend:
    image: devopsfaith/krakend
    container_name: api_gateway
    volumes:
      - ./infra/krakend/krakend.json:/etc/krakend/krakend.json
    ports:
      - "8080:8080"
    networks:
      - backend

  api:
    build: ./apps/api
    container_name: api_rest
    ports:
      - "5001:5001"
    networks:
      - backend

  auth:
    build: ./apps/auth
    container_name: auth_jwt
    ports:
      - "5002:5002"
    networks:
      - backend

networks:
  backend:
    driver: bridge
