import os


class Config:
    SQLALCHEMY_DATABASE_URI = os.getenv("DATABASE_URL")
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_ECHO = False
    SECRET_KEY = os.getenv("SECRET_KEY")
    DEBUG = os.getenv("DEBUG")
    TESTING = False
    ENV = os.getenv("ENV")
    LOG_LEVEL = os.getenv("LOG_LEVEL")
    LOG_FILE = os.getenv("LOG_FILE")

    # Config
    REPOSITORY_TYPE = os.getenv("REPOSITORY_TYPE") # "MEMORY" / "POSTGRES"

    # APP
    APP_NAME = os.getenv("APP_NAME")
    APP_VERSION = os.getenv("APP_VERSION")
    APP_DESCRIPTION = os.getenv("APP_DESCRIPTION")
    APP_TERMS = os.getenv("APP_TERMS")
    APP_CONTACT = os.getenv("APP_CONTACT")

    # API
    API_TITLE = os.getenv("API_TITLE")
    API_VERSION = os.getenv("API_VERSION")
    API_DESCRIPTION = os.getenv("API_DESCRIPTION")
    API_TERMS = os.getenv("API_TERMS")
    API_CONTACT = os.getenv("API_CONTACT")
    API_LICENSE = os.getenv("API_LICENSE")
    API_LICENSE_URL = os.getenv("API_LICENSE_URL")
    API_SECURITY = os.getenv("API_SECURITY")
    API_SECURITY_NAME = os.getenv("API_SECURITY_NAME")
    API_SECURITY_LOCATION = os.getenv("API_SECURITY_LOCATION")
    API_SERVER = os.getenv("API_SERVER")
    API_SERVER_DESCRIPTION = os.getenv("API_SERVER_DESCRIPTION")

    # CORS
    CORS_ORIGIN_WHITELIST = os.getenv("CORS_ORIGIN_WHITELIST")
    CORS_METHODS = os.getenv("CORS_METHODS")
    CORS_ALLOW_HEADERS = os.getenv("CORS_ALLOW_HEADERS")
    CORS_EXPOSE_HEADERS = os.getenv("CORS_EXPOSE_HEADERS")
    CORS_SUPPORTS_CREDENTIALS = os.getenv("CORS_SUPPORTS_CREDENTIALS")

    # JWT
    JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
    JWT_ACCESS_TOKEN_EXPIRES = os.getenv("JWT_ACCESS_TOKEN_EXPIRES")
    JWT_REFRESH_TOKEN_EXPIRES = os.getenv("JWT_REFRESH_TOKEN_EXPIRES")
    JWT_BLACKLIST_ENABLED = os.getenv("JWT_BLACKLIST_ENABLED")
