"""01_Suppression_gender_and_birthdate_and_add_relation_user_to_country

Revision ID: 94d23127df3b
Revises: 6f98e7db9951
Create Date: 2025-04-22 19:55:41.453959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d23127df3b'
down_revision: Union[str, None] = '6f98e7db9951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'user', 'country', ['country_id'], ['id'])
    op.drop_column('user', 'gender')
    op.drop_column('user', 'birthdate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthdate', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'country_id')
    # ### end Alembic commands ###
